---
- hosts: all
  sudo: yes
  tasks:
    - debug:
       msg: " System {{ inventory_hostname }} had major nic name: {{ ansible_default_ipv4.interface }}"
    - package:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - python-pip
        - python-devel
        - gcc
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - pip
    - shell: hostname
      register: result
    - debug:
        var: result
